<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerV97Bxx3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerV97Bxx3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerV97Bxx3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerV97Bxx3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerV97Bxx3\App_KernelDevDebugContainer([
    'container.build_hash' => 'V97Bxx3',
    'container.build_id' => '86c4aea9',
    'container.build_time' => 1649853335,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerV97Bxx3');
